import React from "react";
import Head from "next/head";
import About from "../common/UI/AboutUs/About.jsx";

const about = () => {
  return (
    <div>
      <Head>
        <title>ShipTech-Icon - About Us</title>
        <meta name="description" content="Generated by create next app" />
        {/* favicon */}
        <link
          rel="shortcut icon"
          href="/assets/icons/logo.png"
          type="image/x-icon"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="anime.min.js"></script>
      </Head>

      <About />
    </div>
  );
};

export default about;
