import React from 'react'
import Head from "next/head";
import Designs from '../common/UI/Designs/Designs'

const designs = () => {
  return (
    <div>
      <Head>
        <title>ShipTech-Icon - Our Designs</title>
        <meta name="description" content="Generated by create next app" />
        {/* favicon */}
        <link
          rel="shortcut icon"
          href="/assets/icons/logo.png"
          type="image/x-icon"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="anime.min.js"></script>
      </Head>
        <Designs/>
    </div>
  )
}

export default designs